### ISSUE TITLE
Add example of CKeditor-enabled prop field to the default content

### ISSUE THREAD

**Issue by miloskroulik** [phenaproxima/xb-demo#55]
By [modification of `demo_design_system`](https://drupal.slack.com/archives/C072JMEPUS1/p1747288834565389) it's possible to enable editing of paragraph prop in CKeditor. But I believe that this feature should be also enabled in the default content, but I would like to discuss the part of it.

It works (in `0.3.0-alpha1`) with following component definition:

```
"content" => [
  "sourceType" => "static:field_item:text_long",
  "value" =>
  ["value" => "Easily create the digital experiences you want with Drupal.", "format" => "xb_html_block"],
  "expression" => "ℹ︎text_long␟value",
  "sourceTypeSettings" => [
    "instance" => ["allowed_formats" => ["xb_html_block"]]
  ]
],
```

**Comment by goba** [comment]
I can't open that link you posted. Was the demo design system modified or are you proposing a modification to be made to the demo design system? (I agree a CKEditor enabled field would be great in the demo).

**Comment by goba** [comment]
`experience_builder/tests/modules/sdc_test_all_props/components/all-props/all-props.component.yml` has these which indicate that I probably did the above right, why did it not work then?

```
    #
    # HTML props using `contentMediaType: text/html`
    # @see docs/shape-matching-into-field-types.md#3.2.1
    test_string_html_inline:
      title: 'String with HTML formatting (inline)'
      type: string
      contentMediaType: text/html
      x-formatting-context: inline
      examples:
        - 'This is <strong>bold</strong> and <em>italics</em> text with a <a href="https://example.com">link</a>'
    test_string_html_block:
      title: 'String with HTML formatting (block)'
      type: string
      contentMediaType: text/html
      x-formatting-context: block
      examples:
        - '<p>This is a paragraph with <strong>bold</strong> text.</p><ul><li>List item 1</li><li>List item 2</li></ul>'
```

**Comment by goba** [comment]
Ok the text formats were missing. This way we need to add the contentMediaType and x-formatting-context to a component, such as testimonial:

```
    quote:
      type: string
      $ref: json-schema-definitions://experience_builder.module/textarea
      contentMediaType: text/html
      x-formatting-context: inline
      title: Quote
      description: The quote at the top.
      examples:
        - 'For our 1000+ websites, one of the benefits of Drupal is that accessiblity compliance is already covered.'
```

Newly added copies of this will use CKEditor. It is exported with HTML encoded in `inputs: '{"quote":{"value":` but no additional keys on the component storage that I can see. 

Finally the template needs to be modified to not escape the HTML:

```
      <div class="starshot-testimonial">
        {% if quote %}
          <p class="starshot-testimonial__quote">
            “{{ quote|raw }}”
          </p>
        {% endif %}
```

Unfortunately this is not quite enough as nested p tags in HTML are not valid, so this will result in a nice result :D 

<img width="1526" height="905" alt="Image" src="https://github.com/user-attachments/assets/69d6836c-1989-498f-ab7c-62376052d457" />
